name: Deploy to S3 and Invalidate CloudFront

  on:
    push:
      branches:
        - main
        - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build Vite app for S3
        run: |
          if [ "$GITHUB_REF_NAME" = "main" ]; then
            export VITE_BASE_PATH="/"
          else
            export VITE_BASE_PATH="/"
          fi
          pnpm run build

      - name: Sync to S3
        run: |
          cd dist
          if [ "$GITHUB_REF_NAME" = "main" ]; then
            aws s3 sync . s3://${{ secrets.PROD_S3_BUCKET_NAME }} --delete
          else
            aws s3 sync . s3://${{ secrets.DEV_S3_BUCKET_NAME }} --delete
          fi

      - name: Invalidate CloudFront
        env:
          PROD_CF_ID: ${{ secrets.PROD_CLOUDFRONT_DISTRIBUTION_ID }}
          DEV_CF_ID: ${{ secrets.DEV_CLOUDFRONT_DISTRIBUTION_ID }}
        run: |
          if [ "$GITHUB_REF_NAME" = "main" ]; then
            CF_ID=$PROD_CF_ID
          else
            CF_ID=$DEV_CF_ID
          fi
          if [ -n "$CF_ID" ]; then
            aws cloudfront create-invalidation --distribution-id $CF_ID --paths "/*"
          else
            echo "CloudFront distribution ID not set for this branch. Skipping invalidation."
          fi 