name: Test and Deploy React App to S3

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

env:
  NODE_VERSION: '20'
  PNPM_VERSION: '8'

jobs:
  test:
    name: Run Tests and Linting
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
          
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
          
      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
            
      - name: Install dependencies
        working-directory: ./palestine-solidarity-app
        run: pnpm install --no-frozen-lockfile
        
      - name: Run ESLint (allow warnings)
        working-directory: ./palestine-solidarity-app
        run: pnpm run lint --max-warnings=50
        continue-on-error: true
        
      - name: Build application
        working-directory: ./palestine-solidarity-app
        run: |
          echo "Building React app..."
          pnpm run build
          echo "Build completed. Checking output..."
          ls -la dist/
          echo "Checking for assets..."
          ls -la dist/assets/ || echo "No assets folder found"
        
      - name: Verify build output
        working-directory: ./palestine-solidarity-app
        run: |
          if [ ! -d "dist" ]; then
            echo "ERROR: dist directory not found!"
            exit 1
          fi
          if [ ! -f "dist/index.html" ]; then
            echo "ERROR: index.html not found in dist!"
            exit 1
          fi
          if [ ! -d "dist/assets" ]; then
            echo "ERROR: assets directory not found in dist!"
            exit 1
          fi
          echo "✅ Build verification passed"
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files-${{ github.sha }}
          path: ./palestine-solidarity-app/dist/
          retention-days: 1

  deploy-dev:
    name: Deploy to Development S3
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
    
    environment:
      name: development
      url: ${{ steps.deploy.outputs.website-url }}
    
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-files-${{ github.sha }}
          path: ./dist
          
      - name: Verify downloaded artifacts
        run: |
          echo "Checking downloaded artifacts..."
          ls -la ./dist/
          ls -la ./dist/assets/ || echo "No assets folder in downloaded artifacts"
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Deploy to S3 Development Bucket
        id: deploy
        run: |
          echo "Deploying to S3..."
          aws s3 sync ./dist s3://${{ secrets.DEV_S3_BUCKET_NAME }} --delete --cache-control "max-age=86400"
          echo "Deployment completed"
          echo "website-url=https://${{ secrets.DEV_S3_BUCKET_NAME }}.s3-website-${{ secrets.AWS_REGION }}.amazonaws.com" >> $GITHUB_OUTPUT
          
      - name: Set S3 bucket website configuration
        run: |
          aws s3 website s3://${{ secrets.DEV_S3_BUCKET_NAME }} --index-document index.html --error-document index.html
          
      - name: Invalidate CloudFront Distribution (if configured)
        if: ${{ vars.DEV_CLOUDFRONT_DISTRIBUTION_ID }}
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ vars.DEV_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"

  deploy-prod:
    name: Deploy to Production S3
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    environment:
      name: production
      url: ${{ steps.deploy.outputs.website-url }}
    
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-files-${{ github.sha }}
          path: ./dist
          
      - name: Verify downloaded artifacts
        run: |
          echo "Checking downloaded artifacts..."
          ls -la ./dist/
          ls -la ./dist/assets/ || echo "No assets folder in downloaded artifacts"
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Deploy to S3 Production Bucket
        id: deploy
        run: |
          echo "Deploying to S3..."
          aws s3 sync ./dist s3://${{ secrets.PROD_S3_BUCKET_NAME }} --delete --cache-control "max-age=31536000"
          echo "Deployment completed"
          echo "website-url=https://${{ secrets.PROD_S3_BUCKET_NAME }}.s3-website-${{ secrets.AWS_REGION }}.amazonaws.com" >> $GITHUB_OUTPUT
          
      - name: Set S3 bucket website configuration
        run: |
          aws s3 website s3://${{ secrets.PROD_S3_BUCKET_NAME }} --index-document index.html --error-document index.html
          
      - name: Invalidate CloudFront Distribution (if configured)
        if: ${{ vars.PROD_CLOUDFRONT_DISTRIBUTION_ID }}
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ vars.PROD_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
          
      - name: Notify deployment success
        run: |
          echo "🚀 Production deployment successful!"
          echo "Website URL: ${{ steps.deploy.outputs.website-url }}"

